/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinQrCodeRouteImport } from './routes/join.$qrCode'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedChatLuciaRouteImport } from './routes/_authenticated/chat.lucia'
import { Route as AuthenticatedChatMatchIdRouteImport } from './routes/_authenticated/chat.$matchId'
import { Route as AuthenticatedAppPremiumRouteImport } from './routes/_authenticated/_app/premium'
import { Route as AuthenticatedAppPaymentRouteImport } from './routes/_authenticated/_app/payment'
import { Route as AuthenticatedAppMeRouteImport } from './routes/_authenticated/_app/me'
import { Route as AuthenticatedAppMatchesRouteImport } from './routes/_authenticated/_app/matches'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/_app/discover'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAppProfileEditRouteImport } from './routes/_authenticated/_app/profile.edit'
import { Route as AuthenticatedAppPaymentSuccessRouteImport } from './routes/_authenticated/_app/payment_.success'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminReportsRouteImport } from './routes/_authenticated/_admin/admin.reports'
import { Route as AuthenticatedAdminAdminGymsRouteImport } from './routes/_authenticated/_admin/admin.gyms'
import { Route as AuthenticatedAdminAdminAnnouncementsRouteImport } from './routes/_authenticated/_admin/admin.announcements'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinQrCodeRoute = JoinQrCodeRouteImport.update({
  id: '/join/$qrCode',
  path: '/join/$qrCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatLuciaRoute = AuthenticatedChatLuciaRouteImport.update({
  id: '/chat/lucia',
  path: '/chat/lucia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatMatchIdRoute =
  AuthenticatedChatMatchIdRouteImport.update({
    id: '/chat/$matchId',
    path: '/chat/$matchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPremiumRoute = AuthenticatedAppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaymentRoute = AuthenticatedAppPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMeRoute = AuthenticatedAppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMatchesRoute = AuthenticatedAppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppProfileEditRoute =
  AuthenticatedAppProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPaymentSuccessRoute =
  AuthenticatedAppPaymentSuccessRouteImport.update({
    id: '/payment_/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminReportsRoute =
  AuthenticatedAdminAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminGymsRoute =
  AuthenticatedAdminAdminGymsRouteImport.update({
    id: '/admin/gyms',
    path: '/admin/gyms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAnnouncementsRoute =
  AuthenticatedAdminAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/join/$qrCode': typeof JoinQrCodeRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/matches': typeof AuthenticatedAppMatchesRoute
  '/me': typeof AuthenticatedAppMeRoute
  '/payment': typeof AuthenticatedAppPaymentRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/chat/lucia': typeof AuthenticatedChatLuciaRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRoute
  '/admin/gyms': typeof AuthenticatedAdminAdminGymsRoute
  '/admin/reports': typeof AuthenticatedAdminAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/payment/success': typeof AuthenticatedAppPaymentSuccessRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/join/$qrCode': typeof JoinQrCodeRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/matches': typeof AuthenticatedAppMatchesRoute
  '/me': typeof AuthenticatedAppMeRoute
  '/payment': typeof AuthenticatedAppPaymentRoute
  '/premium': typeof AuthenticatedAppPremiumRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/chat/lucia': typeof AuthenticatedChatLuciaRoute
  '/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRoute
  '/admin/gyms': typeof AuthenticatedAdminAdminGymsRoute
  '/admin/reports': typeof AuthenticatedAdminAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/payment/success': typeof AuthenticatedAppPaymentSuccessRoute
  '/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/join/$qrCode': typeof JoinQrCodeRoute
  '/_authenticated/_app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/_app/matches': typeof AuthenticatedAppMatchesRoute
  '/_authenticated/_app/me': typeof AuthenticatedAppMeRoute
  '/_authenticated/_app/payment': typeof AuthenticatedAppPaymentRoute
  '/_authenticated/_app/premium': typeof AuthenticatedAppPremiumRoute
  '/_authenticated/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/_authenticated/chat/lucia': typeof AuthenticatedChatLuciaRoute
  '/_authenticated/_admin/admin/announcements': typeof AuthenticatedAdminAdminAnnouncementsRoute
  '/_authenticated/_admin/admin/gyms': typeof AuthenticatedAdminAdminGymsRoute
  '/_authenticated/_admin/admin/reports': typeof AuthenticatedAdminAdminReportsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_app/payment_/success': typeof AuthenticatedAppPaymentSuccessRoute
  '/_authenticated/_app/profile/edit': typeof AuthenticatedAppProfileEditRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/join/$qrCode'
    | '/discover'
    | '/matches'
    | '/me'
    | '/payment'
    | '/premium'
    | '/chat/$matchId'
    | '/chat/lucia'
    | '/admin/announcements'
    | '/admin/gyms'
    | '/admin/reports'
    | '/admin/users'
    | '/payment/success'
    | '/profile/edit'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/join/$qrCode'
    | '/discover'
    | '/matches'
    | '/me'
    | '/payment'
    | '/premium'
    | '/chat/$matchId'
    | '/chat/lucia'
    | '/admin/announcements'
    | '/admin/gyms'
    | '/admin/reports'
    | '/admin/users'
    | '/payment/success'
    | '/profile/edit'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/join/$qrCode'
    | '/_authenticated/_app/discover'
    | '/_authenticated/_app/matches'
    | '/_authenticated/_app/me'
    | '/_authenticated/_app/payment'
    | '/_authenticated/_app/premium'
    | '/_authenticated/chat/$matchId'
    | '/_authenticated/chat/lucia'
    | '/_authenticated/_admin/admin/announcements'
    | '/_authenticated/_admin/admin/gyms'
    | '/_authenticated/_admin/admin/reports'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_app/payment_/success'
    | '/_authenticated/_app/profile/edit'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinQrCodeRoute: typeof JoinQrCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$qrCode': {
      id: '/join/$qrCode'
      path: '/join/$qrCode'
      fullPath: '/join/$qrCode'
      preLoaderRoute: typeof JoinQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/lucia': {
      id: '/_authenticated/chat/lucia'
      path: '/chat/lucia'
      fullPath: '/chat/lucia'
      preLoaderRoute: typeof AuthenticatedChatLuciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$matchId': {
      id: '/_authenticated/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AuthenticatedChatMatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/premium': {
      id: '/_authenticated/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedAppPremiumRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/payment': {
      id: '/_authenticated/_app/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AuthenticatedAppPaymentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/me': {
      id: '/_authenticated/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedAppMeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/matches': {
      id: '/_authenticated/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedAppMatchesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/discover': {
      id: '/_authenticated/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_app/profile/edit': {
      id: '/_authenticated/_app/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedAppProfileEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/payment_/success': {
      id: '/_authenticated/_app/payment_/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedAppPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/reports': {
      id: '/_authenticated/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/gyms': {
      id: '/_authenticated/_admin/admin/gyms'
      path: '/admin/gyms'
      fullPath: '/admin/gyms'
      preLoaderRoute: typeof AuthenticatedAdminAdminGymsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/announcements': {
      id: '/_authenticated/_admin/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAnnouncementsRoute: typeof AuthenticatedAdminAdminAnnouncementsRoute
  AuthenticatedAdminAdminGymsRoute: typeof AuthenticatedAdminAdminGymsRoute
  AuthenticatedAdminAdminReportsRoute: typeof AuthenticatedAdminAdminReportsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAnnouncementsRoute:
    AuthenticatedAdminAdminAnnouncementsRoute,
  AuthenticatedAdminAdminGymsRoute: AuthenticatedAdminAdminGymsRoute,
  AuthenticatedAdminAdminReportsRoute: AuthenticatedAdminAdminReportsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppMatchesRoute: typeof AuthenticatedAppMatchesRoute
  AuthenticatedAppMeRoute: typeof AuthenticatedAppMeRoute
  AuthenticatedAppPaymentRoute: typeof AuthenticatedAppPaymentRoute
  AuthenticatedAppPremiumRoute: typeof AuthenticatedAppPremiumRoute
  AuthenticatedAppPaymentSuccessRoute: typeof AuthenticatedAppPaymentSuccessRoute
  AuthenticatedAppProfileEditRoute: typeof AuthenticatedAppProfileEditRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppMatchesRoute: AuthenticatedAppMatchesRoute,
  AuthenticatedAppMeRoute: AuthenticatedAppMeRoute,
  AuthenticatedAppPaymentRoute: AuthenticatedAppPaymentRoute,
  AuthenticatedAppPremiumRoute: AuthenticatedAppPremiumRoute,
  AuthenticatedAppPaymentSuccessRoute: AuthenticatedAppPaymentSuccessRoute,
  AuthenticatedAppProfileEditRoute: AuthenticatedAppProfileEditRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedChatMatchIdRoute: typeof AuthenticatedChatMatchIdRoute
  AuthenticatedChatLuciaRoute: typeof AuthenticatedChatLuciaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedChatMatchIdRoute: AuthenticatedChatMatchIdRoute,
  AuthenticatedChatLuciaRoute: AuthenticatedChatLuciaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinQrCodeRoute: JoinQrCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
